document.querySelector('.cross').style.display='none';
document.querySelector('.hamburger').addEventListener("click",()=>{
    document.querySelector('.sidebaar').classList.toggle('sidebaarGo');
    if(document.querySelector('.sidebaar').classList.contains('sidebaarGo')){
        document.querySelector('.ham').style.display='inline';
        document.querySelector('.cross').style.display='none';
    }
    else{
        document.querySelector('.ham').style.display='none';
        setTimeout(()=>{
        document.querySelector('.cross').style.display='inline';
    },300)
    }
})